ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  HABITAT_SIM_V0:
    ALLOW_SLIDING: false
    ENABLE_PHYSICS: true
    GPU_DEVICE_ID: 0
    GPU_GPU: false
    PHYSICS_CONFIG_FILE: /home/catkin_ws/src/habitat_ros_interface/data/default.physics_config.json
TASK:
  TYPE: Nav-v0

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
DATASET:
  DATA_PATH: /home/catkin_ws/src/habitat_ros_interface/data/datasets/rearrange/mp3d/v1/test/content/Vvot9Ly1tCj0.json.gz
  SCENES_DIR: /home/catkin_ws/src/habitat_ros_interface/data/scene_datasets/mp3d/
  SPLIT: test
  TYPE: PointNav-v1